### PR TITLE
we have added 2 python files and a docs file

### PR DESCRIPTION
**Pull request by Barres121**
we have created two python files and a readme file.

### CODE REVIEW

**Comment by Doc-Njila** [comment]
files and attachments are all good. move on

**Comment by Nelvis1** [comment]
its perfect, continue

**Comment by Nelvis1** [comment]
Creating a Conflict in Git

To intentionally create a merge conflict in Git, you need to follow a
series of steps that involve modifying the same lines of a file in
different branches. Here’s a simple guide to help you achieve this:

1. Initialize a New Git Repository:
   Start by creating a new directory and initializing it as a Git
repository.
   bash
   mkdir git-merge-test
   cd git-merge-test
   git init


2. Create a File and Make an Initial Commit:
   Create a text file and add some content to it. Then, commit this file.
   bash
   echo "foo: foo" > example.txt
   git add example.txt
   git commit -m "Initial commit with example.txt"


3. Create a New Branch:
   Create a new branch from the main branch.
   bash
   git checkout -b branch1


4. Modify the File in the First Branch:
   Change the content of the file in this branch and commit the changes.
   bash
   echo "foo: bar" > example.txt
   git add example.txt
   git commit -m "Change foo to bar in branch1"


5. Switch Back to the Main Branch:
   Now, switch back to the main branch.
   bash
   git checkout main


6. Create Another Branch:
   Create another branch from the main branch.
   bash
   git checkout -b branch2


7. Modify the Same Line in the Second Branch:
   Change the same line in the file in this new branch and commit the
changes.
   bash
   echo "foo: baz" > example.txt
   git add example.txt
   git commit -m "Change foo to baz in branch2"


8. Merge the Branches:
   Now, try to merge branch1 into main. This will create a conflict because
both branches modified the same line in example.txt.
   bash
   git checkout main
   git merge branch1


   When you attempt to merge branch2 next, Git will report a conflict due
to the changes made in both branches [𝟏].

Resolving the Conflict

When you encounter a merge conflict, Git will mark the conflicted areas in
the file. You can resolve the conflict by editing the file to your desired
state and then staging the changes before completing the merge.

This process effectively demonstrates how to create and handle merge
conflicts in Git! If you have any further questions or need clarification,
feel free to ask!

📚 Sources
1. How to best intentionally create a merge conflict? : r/git •
https://www.reddit.com/r/git/comments/b3wm1j/how_to_best_intentionally_create_a_merge_conflict/

**Comment by Nelvis1** [comment]
Quick Steps to Create a Conflict in Git

1. Initialize a Git Repository:
   bash
   mkdir git-merge-test
   cd git-merge-test
   git init


2. Create and Commit a File:
   bash
   echo "Initial content" > example.txt
   git add example.txt
   git commit -m "Initial commit"


3. Modify in Branch 1:
   bash
   git checkout -b branch1
   echo "Change from branch1" > example.txt
   git add example.txt
   git commit -m "Change in branch1"


4. Modify in Branch 2:
   bash
   git checkout main
   git checkout -b branch2
   echo "Change from branch2" > example.txt
   git add example.txt
   git commit -m "Change in branch2"


5. Merge to Create Conflict:
   bash
   git checkout main
   git merge branch1


These steps will create a merge conflict in Git! Let me know if you need
help with anything else!

**Pull request merged**
